"""discussion_reconstruction

Revision ID: 0002_discussion_reconstruction
Revises: 0001_initial
Create Date: 2026-07-20 23:52:16.054853

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002_discussion_reconstruction"
down_revision: str | Sequence[str] | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Defensive: no-op on Neon (already enabled), needed for a fresh
    # docker-compose Postgres that hasn't had it enabled manually.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discussion_units",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.String(length=16), nullable=True),
        sa.Column(
            "participant_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("signal_close_requested", sa.Boolean(), nullable=False),
        sa.Column(
            "last_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_discussion_units_project_channel_status",
        "discussion_units",
        ["project_id", "channel_id", "status"],
        unique=False,
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("discussion_unit_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "matched_keywords",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("embedding_score", sa.Float(), nullable=False),
        sa.Column("reaction_signal", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["discussion_unit_id"],
            ["discussion_units.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("messages", sa.Column("discussion_unit_id", sa.UUID(), nullable=True))
    op.add_column(
        "messages",
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
    )
    op.create_foreign_key(None, "messages", "discussion_units", ["discussion_unit_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "embedding")
    op.drop_column("messages", "discussion_unit_id")
    op.drop_table("candidates")
    op.drop_index("ix_discussion_units_project_channel_status", table_name="discussion_units")
    op.drop_table("discussion_units")
    # ### end Alembic commands ###
